version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-laravel-firebase
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: laravel-firebase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
